name: Python Tests

on:
  push:
    branches:
      - section04  # This will run on pushes to section04
  pull_request:
    branches:
      - section04  # This will also run on PRs to section04

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'  # Specify your Python version

      